### ISSUE TITLE
使用spider163 mp3 --playlist无法下载mp3

### ISSUE THREAD

**Issue by palysoysauce** [Chengyumeng/spider163#11]
显示如下：
[root@mmmm spider163]# spider163 mp3 --playlist 409933862
正在下载歌曲 爱情废柴-周杰伦.mp3
执行抓取任务遭遇配置异常： Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
Google了一下，也不知道怎么解决。
请问是什么原因？

**Comment by Chengyumeng** [comment]
请提供一下程序版本，目前在我本地亲测是可以下载相关mp3的，以及你的操作系统。感觉好像是你的程序配置未更新，没有URL。

**Comment by palysoysauce** [comment]
您好，这个问题我已经解决了。
修改/usr/lib/python2.7/site-packages/spider163/spider/settings.py中的username和password。
删除settings.pyc
重新编译settings.py：python -m settings.py
就可以下载MP3了。
但我发现一个问题。
无法对有特殊符号的歌曲名进行下载，如下：
正在下载歌曲 Bathroom Mirror / You're Coming Right?-Justin Hurwitz.mp3
执行抓取任务遭遇配置异常： [Errno 2] No such file or directory: "./Bathroom Mirror / You're Coming Right?-Justin Hurwitz.mp3"

**Comment by Chengyumeng** [comment]
ok我会着手修复这个问题

**Comment by Chengyumeng** [comment]
该问题在Spider163 2.6.2版本解决。

**Comment by palysoysauce** [comment]
感谢~
还有，可不可以跳过下载出错的歌曲呢？

**Comment by Chengyumeng** [comment]
会考虑增加这个问题，现在避免跳过下载出错的歌曲可以快速发现问题、解决问题。
