### ISSUE TITLE
MP3下载优化建议。

### ISSUE THREAD

**Issue by palysoysauce** [Chengyumeng/spider163#12]
MP3下载过程中，报错就会停止下载。
这个报错可能原因：歌单中的歌曲要单曲购买（即使是会员也得买的），或者没有版权（界面显示为灰色）。
所以我建议：
1、报错的歌曲跳过，继续进行下一首下载。
2、下载之前显示歌单有多少首歌曲。下载完成后，能够统计成功下载的有多少，失败的有多少。

**Comment by Chengyumeng** [comment]
可以提供下报错歌单吗？

**Comment by palysoysauce** [comment]
http://music.163.com/playlist?id=60198&userid=40314095
这个歌单是美国Billboard周榜。
我的报错如下：
[root@localhost ~]# spider163 mp3 --playlist='60198'
正在下载歌曲 Perfect Duet (with Beyoncé)-Ed Sheeran.mp3
正在下载歌曲 rockstar-Post Malone.mp3
正在下载歌曲 Havana-Camila Cabello.mp3
正在下载歌曲 Gucci Gang-Lil Pump.mp3
正在下载歌曲 No Limit-G-Eazy.mp3
正在下载歌曲 Thunder-Imagine Dragons.mp3
执行抓取任务遭遇配置异常： Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
Thunder这首歌，是需要单独付钱的——单曲购买，或者订购整个专辑
--------------------
希望可以跳过报错的歌曲继续下载。
谢谢~~

**Comment by ijayden-lung** [comment]
这个应该不用报错歌单吧，就是抛出异常的时候跳过，不要立即结束就可以了。最后出结果的时候报告一下就ok。

**Comment by Chengyumeng** [comment]
![image](https://user-images.githubusercontent.com/15684846/34555183-63151dce-f16b-11e7-9501-ba036a3b71c9.png)
已定位该问题，会想办法近期修复

**Comment by Chengyumeng** [comment]
暂停解决方案：跳过付费购买歌曲，最后给出下载报表

**Comment by Chengyumeng** [comment]
该问题已经解决，预计在一周内的下一个发行版提供更新！
![image](https://user-images.githubusercontent.com/15684846/34566334-1cad1f0c-f199-11e7-86f5-3fd614e8aea6.png)
