### ISSUE TITLE
可以抓取自己的听歌记录吗？

### ISSUE THREAD

**Issue by ijayden-lung** [chengyumeng/spider163#13]
我觉得网易云的年度报告太差了，不符合我的要求，我想获得自己月听歌记录，季度听歌记录，年听歌记录个总听歌记录之类，然后可以按自己喜欢的方面去做报告。
希望可能增加的功能的有，获得用户的听歌记录，raw data 包括听每一首歌的时间，歌手，专辑，歌词，风格等信息

进阶数据，做一个类似于网易云的总结，歌曲排行，专辑排行（专辑里面所有歌都应该至少被听过一遍，进阶有专辑里面歌曲排行），歌手排行（进阶有歌手里面歌曲排行），风格排行（进阶里面有同风格的歌曲排行），连续单曲循环排行（不能中断，又开始时间，结束时间），歌词排行（进阶可以看到歌词对应的歌曲）
万分感谢~(*^__^*) 嘻嘻……

**Comment by ijayden-lung** [comment]
建议继续增加下载专辑，下载歌手的歌曲功能。

**Comment by Chengyumeng** [comment]
听歌记录的API目测权限很小，下载专辑和歌手的功能在考虑中，感谢建议！

**Comment by ijayden-lung** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%8e%b7%e5%8f%96%e7%94%a8%e6%88%b7%e6%92%ad%e6%94%be%e8%ae%b0%e5%bd%95
貌似这个API可以获取用户的听歌记录

**Comment by ijayden-lung** [comment]
不过这个api还是只能获取网易云给出的每周和所有时间听歌记录，并不能获得听歌记录的raw data

**Comment by Chengyumeng** [comment]
正因为那个API数据不全，所以不太方便做的比较完善。
