### ISSUE TITLE
执行抓取任务遭遇配置异常

### ISSUE THREAD

**Issue by ijayden-lung** [Chengyumeng/spider163#15]
抓取我的歌单的时候，出现了这个问题，不知道是什么意思，其他的歌单都没有问题，就这个歌单有问题。
spider163 get --playlist 127473345
执行抓取任务遭遇配置异常： 'NoneType' object has no attribute 'encode'

**Comment by Chengyumeng** [comment]
这个问题主要是因为网易云音乐缺少部分数据字段，会在后续更新中修复该问题。

**Comment by Chengyumeng** [comment]
pip install spider163==2.6.3 解决该问题。
