### ISSUE TITLE
谁发下window下的安装说明，试了几次都不成功

### ISSUE THREAD

**Issue by ncuu** [Chengyumeng/spider163#16]
谁发下window下的安装说明，试了几次都不成功

**Comment by Chengyumeng** [comment]
对window的支持有限，并没有做过相关测试，暂时也没有这个计划，建议跑个linux虚拟机。

**Comment by ncuu** [comment]
linux的安装说明有吗，不太懂

**Comment by Chengyumeng** [comment]
自行百度就可以~

**Comment by ncuu** [comment]
linux我有，想知道怎么做到web方便操作，有说明书吗，谢谢老大，其实开始我只是想下载个歌单，现在魔障了，想搞出来

**Comment by Chengyumeng** [comment]
没有啊，你看一下README.md吧
