### ISSUE TITLE
小白求问 抓取歌单日志一直显示901？

### ISSUE THREAD

**Issue by Bingie** [Chengyumeng/spider163#2]
你好！
想问下，为什么我使用这个命令的时候
`python capture.py --module=music --config=spider163.conf --source=cmd --playlist=720308660`
在日志中一直显示error 901?
`INFO:root:Error 901 : http://music.163.com/playlist?id=720308660`

谢谢

**Comment by Chengyumeng** [comment]
是不是网络问题？我本地测试没有这个问题。
