### ISSUE TITLE
top50 cmd登录那块怎么用？playlist是不是写成palylist了？

### ISSUE THREAD

**Issue by acer-haitao** [Chengyumeng/spider163#23]
1 执行抓取任务遭遇配置异常： HTTPConnectionPool(host='music.163.com', port=80): Max retries exceeded with url: /weapi/login/cellphone (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ffadedb1dd0>, 'Connection to music.163.com timed out. (connect timeout=10)'))

2 Spider163: error: unrecognized arguments: --palylist=389354428

3 执行抓取任务遭遇配置异常： 'NoneType' object has no attribute '__getitem__'这个是数据库的问题吗？

**Comment by Chengyumeng** [comment]
是的，应该是playlist。。歌单ID必须是登录账号有权限的哦。
