### ISSUE TITLE
反爬问题

### ISSUE THREAD

**Issue by WJerry0227** [Chengyumeng/spider163#3]
你好，
我之前也写过一个类似的爬取163的音乐评论。但是房到服务器上跑的时候不一会IP就被封了。后来用了代理但是速度太慢。

我看了您的代码但是没有找到在哪里进行的反爬虫机制。请问您是怎么进行反爬的问题的？

**Comment by Chengyumeng** [comment]
我没有使用代理，但是在全速抓取的过程中，也没有遇到类似反爬虫机制。

**Comment by WJerry0227** [comment]
那你运气还挺好的，可能是我爬太快了？我爬一两个小时就遇到服务器503

**Comment by RominYue** [comment]
遇到反爬虫的限制了。免费的代理ip也慢，只能放慢爬取速度了
