### ISSUE TITLE
依赖很多但是并没有一个freeze文件

### ISSUE THREAD

**Issue by PengFoo** [Chengyumeng/spider163#4]
建议添加freeze文件自动搞定依赖。
要不然需要手动安装非常多的lib，而且也会有问题
比如Crypto库，
pip install Crypto 是错误的
pip install pycrpto 才是正确的。

**Comment by Chengyumeng** [comment]
好的，我会在下次更新中加上，感谢。

**Comment by Chengyumeng** [comment]
您好，requirements.txt已经添加。目前正在着手准备v2.5版本，欢迎持续关注~
