### ISSUE TITLE
初始化数据库出现问题

### ISSUE THREAD

**Issue by Dazmk** [Chengyumeng/spider163#5]
![image](https://user-images.githubusercontent.com/25970235/32831814-7e58e0ec-ca34-11e7-87db-e678042034d9.png)
您好，刚开始是Mysql登录问题，我已经解决了，但是现在出现这个问题，怎么也解决不了，希望能帮忙看一下，指导我怎么解决，谢谢~

**Comment by RominYue** [comment]
可能是mysql版本不对，所以由那个ORM转换执行的sql语句报错。

**Comment by Chengyumeng** [comment]
这个可能是某个数据库字段的格式问题，在其他人那里也遇到过这个问题，在近期我想办法修复一下，在这以前亦可以尝试自己手动建表

**Comment by SEZYUEN** [comment]
刚刚遇到了同样的问题。。。

**Comment by Chengyumeng** [comment]
更新到2.5.3，已经解决了这个问题，请pip install spider163==2.5.3或者源码安装本项目验证。

**Comment by Dazmk** [comment]
![image](https://user-images.githubusercontent.com/25970235/33195004-f8b4656a-d10e-11e7-910e-380488c3dd99.png)
我更新代码之后，还是这个问题。 @SEZYUEN 请问你更新代码之后问题解决了吗？

**Comment by Chengyumeng** [comment]
@Dazmk 请发一下你的配置文件

**Comment by Dazmk** [comment]
![image](https://user-images.githubusercontent.com/25970235/33195254-ede8e2c6-d110-11e7-925d-4ff7c9e3752d.png)
@Chengyumeng 您看一下这个有问题吗？

**Comment by SEZYUEN** [comment]
依然有这个问题，我用的是ANACONDA环境，用源码安装2.5.3，已经成功装上，但运行init.py还是同样的问题。
这是我的配置文件：
![default](https://user-images.githubusercontent.com/33884986/33195653-723b6f82-d114-11e7-8984-ef7f2d6807dd.png)
小白不懂数据库，但我昨天试着谷歌了一下，貌似有可能是建表时出现了问题，但不懂怎么解决。。。
这是一个类似问题的相关链接~https://mariadb.com/kb/en/library/create-table/+comments/459~希望有用~拜托Owner了

**Comment by Chengyumeng** [comment]
@SEZYUEN 你配置文件错了，不能给数据库起名字database啊，把database改成其他的

**Comment by SEZYUEN** [comment]
只用在配置文件里面改名字就可以了吗？？刚刚改了名字了。。。运行了一下，返回了这个东西：
![default](https://user-images.githubusercontent.com/33884986/33197078-3856c4ce-d11e-11e7-98c5-17527ed90c6d.jpg)
是成功了吗？？？

**Comment by Dazmk** [comment]
应该是成功了吧，那个warning：Incorrect string value 是因为数据库字符编码的问题

**Comment by SEZYUEN** [comment]
创建了名为netease的数据库。在MySQL里看得到，这就可以了吗？？
![default](https://user-images.githubusercontent.com/33884986/33197589-6bbf6638-d121-11e7-986f-4f5a64dac31e.png)
那下一步怎么做~我想获取评论数据，直接RUN comment.py 就可以了？？看使用指南是可以指定歌曲id的，但没搞懂要怎么做。
问题略白痴，请赐教，谢谢。

**Comment by Dazmk** [comment]
![image](https://user-images.githubusercontent.com/25970235/33197723-1bb0942c-d122-11e7-93d3-0f04cf2cd616.png)
https://github.com/Chengyumeng/spider163
建议你看一下项目的Readme😃 @SEZYUEN

**Comment by SEZYUEN** [comment]
@Dazmk 这个已经仔细看过了，但还是不知道怎么操作。如果前面设置数据库已经没问题，我想知道下一步具体的操作，十分感谢。

**Comment by Dazmk** [comment]
@SEZYUEN 我不了解你的运行环境，所以我运行的步骤可能和你有些不同，打开终端，cd 到项目文件夹，输入命令运行就行了，比如你想获得周杰伦《晴天》的评论，首先你需要知道晴天的song_id，这个项目好像具有搜索歌曲的功能，你可以自己另行尝试。

这是我去网易云音乐搜的结果:186016

![image](https://user-images.githubusercontent.com/25970235/33198296-27bde172-d125-11e7-8fe6-901eb148f5d1.png)

那么你可以通过执行这条命令把晴天的评论存储到数据库中
$ spider163 comment -s 186016

不过由于项目在我的电脑上还没运行成功，以上都是我个人的理解...
希望可以帮到你..

**Comment by fy916** [comment]
<img width="1141" alt="qq20180220-013347 2x" src="https://user-images.githubusercontent.com/34953238/36390717-f62983e2-15de-11e8-9803-3bacbd4a0b0b.png">
您好 我用终端装完spider之后敲help也出现初始化失败 网上查了也有类似现象 不过似乎都没法解决 希望可以指教 database是64位 应该可以排除不兼容性吧
