### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

### ISSUE THREAD

**Issue by SEZYUEN** [Chengyumeng/spider163#7]
小白提问：在执行init.py出现错误，错误位置在：
  File "C:\Users\SEZYUEN\Anaconda3\lib\configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
错误信息：
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
请问该如何解决？

**Comment by Chengyumeng** [comment]
windows的默认编码好像是gbk，而程序中使用的是utf-8。这多半是因为我在template文件中使用了中文注释的原因，https://github.com/Chengyumeng/spider163/blob/master/spider163/template/spider163.conf
你可以自行修改本地库中的中文注释为英文，我也会作为一个目标，在后续开发中满足跨平台的需求（由于我本人使用mac，没有验证在windows下的效果）。

**Comment by SEZYUEN** [comment]
刚开始把中文全部删除也还是不行。后来查到了有一个很简单的解决方式，用Notepad软件打开spider163.conf，将编码改为以UTF-8无BOM格式编码再保存，就可以了。
