### ISSUE TITLE
由playlist抓取music只能获得第一个music

### ISSUE THREAD

**Issue by RominYue** [Chengyumeng/spider163#9]
看样子api变了。看了code的music_url, 在浏览器试了下，发现返回的json只有列表的第一个曲目。之前这个api还好用来着。
<img width="798" alt="screen shot 2017-12-07 at 00 18 06" src="https://user-images.githubusercontent.com/7324409/33671659-2dc38082-dae3-11e7-9bf9-724cf8f4b237.png">

**Comment by Chengyumeng** [comment]
貌似确实改了，近期（本月）想办法修复一下。

**Comment by Chengyumeng** [comment]
新API格式：http://music.163.com/api/v1/playlist/detail?id=

**Comment by Chengyumeng** [comment]
该问题已经解决，可通过源码安装或者pip install spider1633==2.5.4使用。

**Comment by RominYue** [comment]
新api貌似只能返回歌单前10个music。

**Comment by RominYue** [comment]
<img width="1054" alt="screen shot 2017-12-08 at 20 37 16" src="https://user-images.githubusercontent.com/7324409/33766019-a03a91b8-dc56-11e7-935d-1d3a85cd3393.png">

**Comment by Chengyumeng** [comment]
貌似最新的API需要解密，这个操作起来稍微麻烦一点，近期会支持，暂时只能抓十首。等完善该功能我会在这里说明。

**Comment by RominYue** [comment]
![http://music.163.com/api/v1/playlist/detail?id=](http://music.163.com/api/v1/playlist/detail?id=) 这个api的trackids是显示全部的。如果搞到每首music的detail就可以间接搞定。另外，想问下这些api是怎么测试出来的？我用chrome console分析不出来这些，使用某些抓包工具么

**Comment by Chengyumeng** [comment]
根据网易最新变动api，v2.6.0已经解决该问题。
